# Generated by Django 4.1.7 on 2023-03-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
