# Generated by Django 4.1.7 on 2023-03-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_diary', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
